### ISSUE TITLE
handle must not be null

### ISSUE THREAD

**Issue by AngrryRabbit** [nearprosmith/java-rcs380-test#1]
Hi sir
can u help me ?
1、should i must create a file  /Resourses/javax.usb.properties
      and  put the key-value  : javax.usb.services = org.usb4java.javax.Services
2、jdk  must 1.6 ?

but it still doesn't work,error messge is:

 Connected to the target VM, address: '127.0.0.1:50836', transport: 'socket'
**java.lang.IllegalArgumentException: handle must not be null**
null null
	at org.usb4java.LibUsb.setAutoDetachKernelDriver(Native Method)
	at jp.shanimnni.RCS380.<init>(RCS380.java:47)
	at jp.shanimnni.Main.main(Main.java:19)
Exception in thread "main" java.lang.NullPointerException
	at jp.shanimnni.RCS380.open(RCS380.java:92)
	at jp.shanimnni.Main.main(Main.java:25)
Disconnected from the target VM, address: '127.0.0.1:50836', transport: 'socket'

Process finished with exit code 1

thank you very much !

**Comment by peterzhangnull** [comment]
check your pc usb port product id, then copy your usb product id to RCS380 PRODUCT_ID
